services:
  transaction-service:
    platform: linux/amd64
    image: app.netbird.cloud:8081/be-transaction/stable:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Load environment variables from the .env file in the host
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - DB_TIMEZONE=${DB_TIMEZONE:-Asia/Jakarta}
      - AUTH_VALIDATE_URL=${AUTH_VALIDATE_URL}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL}
    restart: always
