services:
  transaction-service:
    platform: linux/amd64
    image: app.netbird.cloud:8081/be-transaction/stable:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Load environment variables from the .env file in the host
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    restart: always
